### ISSUE TITLE
Can't resolve css background images

### ISSUE THREAD

**Issue by danielLee0721** [clenemt/eleventy-webpack#13]
Is anyone experiencing Module build failure? I am getting the following message:

[start:webpack ] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[start:webpack ] ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
[start:webpack ] Error: Can't resolve '/assets/static/venus-velocity-thumbnail.jpg' in '/Users/daniellee/eleventy-webpack-starter-project-20210412-wedding/src/assets/styles'

Any solutions?

**Comment by EricTalv** [comment]
Did you find a solution for this?
