### ISSUE TITLE
Image shortcode Right angle bracket missing

### ISSUE THREAD

**Issue by arup-official** [clenemt/eleventy-webpack#7]
In shortcode.js the right angle bracket is missing in the [Figure tag](https://github.com/clenemt/eleventy-webpack/blob/8cd4e1ef5cbf8f9e2ec68b2ca5727f27749b54ed/utils/shortcodes.js#L106) 

It will be:
     &lt;figure class="${className ? \`fig-${className}\` : ''}"&gt;

**Comment by clenemt** [comment]
Nice catch, I missed it while porting some code over.
